# This file creates multiple Kubernetes secrets synchronized with Azure Key Vault, as requested
# Refer to `.akvSecrets` in `values.yaml`

{{- $releaseName := include "metadata.releaseName" . -}}
{{- $labels := include "metadata.labels" . -}}
{{- range $k, $v := .Values.akvSecrets }}
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-%s" $releaseName $k }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  vault:
    name: {{ $v.vaultName }}
    object:
      name: {{ $v.secretName }}
      type: {{ $v.secretType }}
      {{- with $v.secretContentType }}
      contentType: {{ . }}
      {{- end }}
  output:
    secret:
      name: {{ printf "%s-%s" $releaseName $k }}
      {{- with $v.targetType }}
      type: {{ . }}
      {{- end }}
      {{- with $v.targetKey }}
      dataKey: {{ . }}
      {{- end }}
{{- end }}
